Instalación de Eclipse

diff --git a/scripts/packages/makefile b/scripts/packages/makefile
--- a/scripts/packages/makefile
+++ b/scripts/packages/makefile
@@ -11,11 +11,11 @@ SHELL := /bin/bash
 
 .PHONY: codeblocks
 codeblocks:
-	$(call apt-install,codeblocks)
+	$(call apt-install,codeblocks, Codeblocks)
 
 .PHONY: lazarus
 lazarus:
-	$(call apt-install,lazarus)
+	$(call apt-install,lazarus, Lazarus)
 
 .PHONY: swi-prolog
 swi-prolog: 
@@ -25,15 +25,24 @@ swi-prolog:
 bluej:
 	@URL=$$(curl -s https://www.bluej.org/ | grep -o "https://www\.bluej\.org/download/files/BlueJ-linux-[0-9]*\.deb"); \
 	PKG_NAME=$$(echo $$URL | grep -o "BlueJ-linux-[0-9]*\.deb");\
-	$(call deb-install,$${URL},$${PKG_NAME},"BlueJ") 
+	$(call deb-install,$${URL},$${PKG_NAME},BlueJ) 
 
+.PHONY: eclipse
+eclipse:
+	@PACKAGE_NAME="eclipse-inst-jre-linux64.tar.gz";\
+	BASE_URL="https://eclipse.c3sl.ufpr.br/oomph/epp/";\
+	LATEST_RELEASE_DATE=$$(curl -s "$$BASE_URL" | grep -Eo "[0-9]{1,4}-[0-9]{1,2}/" | tail -n 1 | grep -Eo "[0-9]{1,4}-[0-9]{1,2}");\
+	RELEASE=$$(curl -s "$${BASE_URL}/$${LATEST_RELEASE_DATE}/" | grep -o "M[0-9]" | tail -n 1);\
+	URL=$${BASE_URL}$${LATEST_RELEASE_DATE}/$${RELEASE}/$${PACKAGE_NAME};\
+	INSTALLER_FILENAME="eclipse-installer/eclipse-inst";\
+	$(call tarball-download,$${URL},$${PACKAGE_NAME},$${INSTALLER_FILENAME},Eclipse)
 
 define apt-install
-	@pkexec -u $$USER sudo apt-get install $1 -y | zenity --progress --pulsate --no-cancel --auto-kill --auto-close --width=350 --text="Instalando paquete..." --title="Instalación de $1"; \
-	if [[ "$$?" = "0" ]]; then \
-		zenity --info --text="Instalación finalizada exitosamente."; \
+	@pkexec -u $$USER sudo apt-get install $1 -y | yad --progress --pulsate --button=gtk-cancel:1 --auto-kill --auto-close --borders=15 --width=350 --text="Instalando paquete..." --title="Instalación de $1"; \
+	if [[ $$? -eq 0 ]]; then \
+		yad --title="Éxito" --text-align=center --width=350 --borders=15 --image=dialog-success --text="$2 instalado correctamente."; \
 	else \
-		zenity --error --text="Ocurrió un error al instalar el paquete."; \
+		yad --title="Error" --text-align=center --width=350 --borders=15 --image=dialog-error --text="Operación cancelada."; \
 	fi
 endef
 
@@ -46,8 +55,14 @@ define deb-install
 		code=$$?;\
 	fi; \
 	if [[ $$code -eq 0 ]]; then \
-		yad --title=Éxito --text="$3 Instalación finalizada." --with=350 --borders=15 --text-align=center --image=dialog-success;\
+		yad --title=Éxito --text="$3 se instaló correctamente." --with=350 --borders=15 --text-align=center --image=dialog-success;\
 	else \
 		yad --title=Error --text="Operación cancelada" --image=dialog-error borders=15 --text-align=center --width=350;\
 	fi
+endef
+
+define tarball-download
+	wget --progress=dot $1 -P /tmp 2>&1 | grep --line-buffered -oP "(\d+(\.\d+)?(?=%))" | yad --progress --button=gtk-cancel:1 --auto-close --borders=15 --width=350 --text="Descargando paquete..." --title="Instalación de $4";\
+	EXEC="tar -xvzf /tmp/$2 -C /tmp; /tmp/$3";\
+	eval $$EXEC | yad --progress --pulsate --auto-kill --auto-close --borders=15 --no-buttons --text="Esperando a que finalice la instalación..." --title="Instalación de $4";\
 endef
